/*@ THIS FILE IS DYNAMICALLY GENERATED BY FORMBUILDER : DO NOT MODIFY @*/



/*@start.button_onclick_id_11@*/
$(function(){$("button[@name='button']").bind("click", /*@*/function(e) {
    e.preventDefault();
    alert('You clicked the |' + $(this).attr('name') + '| button');
}/*@*/);});
/*@end.button_onclick_id_11@*/

/*@start.button_onclick_id_14@*/
$(function(){$("button[@name='button2']").bind("click", /*@*/function(e) {
    if ($.trim($("input[@name='validation_test']").val()) == "") {
        e.preventDefault();
        alert("Please enter your password");
    }
}/*@*/);});
/*@end.button_onclick_id_14@*/

